name: arm-windows

on:
  # Workflow dispatched manually
  workflow_dispatch:
  # Workflow under a monthly Patch Tuesday schedule
  schedule:
  - cron: '30 23 8-14 * 2'

permissions:
  contents: read
  packages: write

jobs:
  # Generate an image with the IAR Build Tools for Arm (Windows)
  # *with* full device support
  arm-windows:
    strategy:
      matrix:
        os: [ 2019 ]
        url: [ "https://netstorage.iar.com/FileStore/STANDARD/001/003/582/cxarm-9.60.4.11196.exe" ]
    runs-on: windows-${{ matrix.os }}
    steps:
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
    - if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - if: github.event_name != 'pull_request'
      run: |
        $url = "${{ matrix.url }}";
        $match = [regex]::match($url,'cx([a-z]+)-(\d+\.\d+\.\d+).*exe');
        $target  = $match.groups[1].value;
        $version = $match.groups[2].value;
        docker build -t ghcr.io/${{ github.repository_owner }}/${target}:${version}-windows -f .github/workflows/Dockerfile-${target}.win-${{ matrix.os }} .github/workflows --build-arg URL=${{ matrix.url }} --build-arg TARGET=${target} --build-arg VERSION=${version};
        docker push ghcr.io/${{ github.repository_owner }}/${target}:${version}-windows;
      shell: pwsh